export const ACHIEVEMENTS = [
  {
    id: 'first_blood',
    emoji: '🩸',
    title: '初嘗滋味',
    description: '蓋下第一枚印章',
    rarity: 'common',
    condition: ({ stamps }) => stamps.length >= 1,
    progress: ({ stamps }) => ({ current: Math.min(stamps.length, 1), max: 1 }),
  },
  {
    id: 'ten_stamps',
    emoji: '🔥',
    title: '怒火十連',
    description: '累積 10 枚印章',
    rarity: 'common',
    condition: ({ stamps }) => stamps.length >= 10,
    progress: ({ stamps }) => ({ current: Math.min(stamps.length, 10), max: 10 }),
  },
  {
    id: 'full_card',
    emoji: '💀',
    title: '集滿離職意志',
    description: '集滿 30 枚印章',
    rarity: 'rare',
    condition: ({ stamps }) => stamps.length >= 30,
    progress: ({ stamps }) => ({ current: Math.min(stamps.length, 30), max: 30 }),
  },
  {
    id: 'centenary',
    emoji: '💯',
    title: '百忍成金',
    description: '累積 100 枚（你還在？）',
    rarity: 'legendary',
    condition: ({ stamps }) => stamps.length >= 100,
    progress: ({ stamps }) => ({ current: Math.min(stamps.length, 100), max: 100 }),
  },
  {
    id: 'first_checkin',
    emoji: '📅',
    title: '第一步',
    description: '完成第一次每日打卡',
    rarity: 'common',
    condition: ({ stamps }) => stamps.filter(s => s.type === 'checkin').length >= 1,
    progress: ({ stamps }) => ({ current: Math.min(stamps.filter(s => s.type === 'checkin').length, 1), max: 1 }),
  },
  {
    id: 'streak_3',
    emoji: '📆',
    title: '三天打魚',
    description: '連續打卡 3 天',
    rarity: 'common',
    condition: ({ streak }) => streak >= 3,
    progress: ({ streak }) => ({ current: Math.min(streak, 3), max: 3 }),
  },
  {
    id: 'streak_7',
    emoji: '🗓️',
    title: '一週忍耐',
    description: '連續打卡 7 天',
    rarity: 'rare',
    condition: ({ streak }) => streak >= 7,
    progress: ({ streak }) => ({ current: Math.min(streak, 7), max: 7 }),
  },
  {
    id: 'streak_30',
    emoji: '🏅',
    title: '月度堅持',
    description: '連續打卡 30 天',
    rarity: 'legendary',
    condition: ({ streak }) => streak >= 30,
    progress: ({ streak }) => ({ current: Math.min(streak, 30), max: 30 }),
  },
  {
    id: 'target_set',
    emoji: '🎯',
    title: '目標設定',
    description: '設定了離職目標日期',
    rarity: 'common',
    condition: ({ targetDate }) => targetDate !== null,
    progress: ({ targetDate }) => ({ current: targetDate ? 1 : 0, max: 1 }),
  },
  {
    id: 'all_events',
    emoji: '🌈',
    title: '職場全收集',
    description: '每種職場事件各蓋一次',
    rarity: 'rare',
    condition: ({ eventCountMap }) => Object.keys(eventCountMap).length >= 10,
    progress: ({ eventCountMap }) => ({ current: Math.min(Object.keys(eventCountMap).length, 10), max: 10 }),
  },
  {
    id: 'overtime_addict',
    emoji: '🌙',
    title: '無薪加班常客',
    description: '無薪加班蓋了 5 次',
    rarity: 'rare',
    condition: ({ eventCountMap }) => (eventCountMap['unpaid_overtime'] || 0) >= 5,
    progress: ({ eventCountMap }) => ({ current: Math.min(eventCountMap['unpaid_overtime'] || 0, 5), max: 5 }),
  },
  {
    id: 'friday_survivor',
    emoji: '😅',
    title: '週五倖存者',
    description: '週五炸彈蓋了 3 次',
    rarity: 'rare',
    condition: ({ eventCountMap }) => (eventCountMap['friday_urgent'] || 0) >= 3,
    progress: ({ eventCountMap }) => ({ current: Math.min(eventCountMap['friday_urgent'] || 0, 3), max: 3 }),
  },
]
