export const ACHIEVEMENTS = [
  {
    id: 'first_blood',
    emoji: '🩸',
    title: '初嘗滋味',
    description: '蓋下第一枚印章',
    condition: ({ stamps }) => stamps.length >= 1,
  },
  {
    id: 'ten_stamps',
    emoji: '🔥',
    title: '怒火十連',
    description: '累積 10 枚印章',
    condition: ({ stamps }) => stamps.length >= 10,
  },
  {
    id: 'full_card',
    emoji: '💀',
    title: '集滿離職意志',
    description: '集滿 30 枚印章',
    condition: ({ stamps }) => stamps.length >= 30,
  },
  {
    id: 'centenary',
    emoji: '💯',
    title: '百忍成金',
    description: '累積 100 枚（你還在？）',
    condition: ({ stamps }) => stamps.length >= 100,
  },
  {
    id: 'first_checkin',
    emoji: '📅',
    title: '第一步',
    description: '完成第一次每日打卡',
    condition: ({ stamps }) => stamps.filter(s => s.type === 'checkin').length >= 1,
  },
  {
    id: 'streak_3',
    emoji: '📆',
    title: '三天打魚',
    description: '連續打卡 3 天',
    condition: ({ streak }) => streak >= 3,
  },
  {
    id: 'streak_7',
    emoji: '🗓️',
    title: '一週忍耐',
    description: '連續打卡 7 天',
    condition: ({ streak }) => streak >= 7,
  },
  {
    id: 'streak_30',
    emoji: '🏅',
    title: '月度堅持',
    description: '連續打卡 30 天',
    condition: ({ streak }) => streak >= 30,
  },
  {
    id: 'target_set',
    emoji: '🎯',
    title: '目標設定',
    description: '設定了離職目標日期',
    condition: ({ targetDate }) => targetDate !== null,
  },
  {
    id: 'all_events',
    emoji: '🌈',
    title: '職場全收集',
    description: '每種職場事件各蓋一次',
    condition: ({ eventCountMap }) => Object.keys(eventCountMap).length >= 10,
  },
  {
    id: 'overtime_addict',
    emoji: '🌙',
    title: '無薪加班常客',
    description: '無薪加班蓋了 5 次',
    condition: ({ eventCountMap }) => (eventCountMap['unpaid_overtime'] || 0) >= 5,
  },
  {
    id: 'friday_survivor',
    emoji: '😅',
    title: '週五倖存者',
    description: '週五炸彈蓋了 3 次',
    condition: ({ eventCountMap }) => (eventCountMap['friday_urgent'] || 0) >= 3,
  },
]
